#182 - Temperature Validation
PharmaLedger-IMI/csc-workspace-main pull request #197
Opened 2021-09-07 11:18 UTC by abhayprasadnovartis

Made changes to make sure that Min Temperature is always <=Max Temperature while the inputs change. Please refer below snapshot
![image](https://user-images.githubusercontent.com/88542564/132336194-1835b82a-bd6c-47e9-bcc6-efccad013606.png)

2021-09-07 12:00 UTC, Mastaleru requested changes
I wanted to add the same handler for both min and max temperature model.
//please avoid duplicate code
`let tempChangehandler = ()=>{
//do validation here
}
//add model change listers

this.model.onChange('form.inputs.keep_between_temperature_max.value',tempChangehandler) 

this.model.onChange('form.inputs.keep_between_temperature_max.value', tempChangehandler)
`

2021-09-08 06:07 UTC, abhayprasadnovartis commented
Implemented the required changes

2021-09-08 08:33 UTC, Mastaleru approved these changes

2021-09-08 08:33 UTC, merged

2021-09-08 08:53 UTC, Mastaleru commented
You copy pasted my indications without testing and add the handler twice for max temperature...