Implemented #350
PharmaLedger-IMI/csc-workspace-main pull request #375
Opened 2021-10-05 11:59 UTC by arispapapro

2021-10-05 12:33 UTC, Mastaleru requested changes
In ShipmentsControllerImpl normalStatuses and approvedStatuses should also take into consideration the actor, right? I think you have to build a service that will return the normal statuses, approvedStatuses and use it where you need. For example in this ShipmentsControllerImpl and in HistoryModalController.Impl.

2021-10-05 12:40 UTC, arispapapro commented
> a

Shall i create a new service for that or place this functionality in an existing one ?

2021-10-05 12:50 UTC, Mastaleru commented
More like a utility service. And I want a new one.

2021-10-06 07:23 UTC, Mastaleru approved these changes

2021-10-06 07:23 UTC, merged