PR for issue #531
PharmaLedger-IMI/csc-workspace-main pull request #548
Opened 2021-11-16 11:02 UTC by arijitnv

2021-11-16 15:21 UTC, Mastaleru requested changes
how does it look like?
paste here a screenshot

2021-11-17 07:29 UTC, arijitnv commented
![image](https://user-images.githubusercontent.com/88488284/142155480-ff7e0d07-058f-4369-9a48-61435e9b52ce.png)

2021-11-17 08:01 UTC, Mastaleru commented
I don't see borders like in the mockup. even if the progress is 0/n, the borders should be visible

2021-11-19 09:51 UTC, Mastaleru approved these changes

2021-11-19 09:51 UTC, merged