Implemented "Show a message when no documents are attached yet." #641
PharmaLedger-IMI/csc-workspace-main pull request #654
Opened 2022-03-22 10:32 UTC by arispapapro

2022-03-22 19:18 UTC, Mastaleru requested changes

2022-03-22 19:18 UTC, Mastaleru commented on csc-courier-ssapp/code/scripts/controllers/EditShipmentController.js
> +      this.model.form.areFilesEmpty = (this.files.length <= 0);
inadequate comparation. arrays length cannot be a negative number

2022-03-22 19:18 UTC, Mastaleru commented on csc-courier-ssapp/code/scripts/controllers/EditShipmentController.js
> +    this.model.form.areFilesEmpty = true;
areFilesEmpty-> hasAttachments

https://www.samanthaming.com/tidbits/34-better-boolean-variable-names/

2022-03-22 19:18 UTC, Mastaleru commented on csc-courier-ssapp/code/pages/edit-shipment.html
> +              <p class='text-center' slot="true">There are no any Files uploaded yet</p>
use bootstrap light alert as you proposed

2022-03-29 07:07 UTC, arispapapro commented
I made the changes rafael you can merge it.

2022-03-29 07:40 UTC, Mastaleru approved these changes

2022-03-29 07:40 UTC, merged