integrate #793 with master.
PharmaLedger-IMI/csc-workspace-main pull request #823
Opened 2022-11-08 10:45 UTC by arispapapro

2022-11-10 10:02 UTC, Mastaleru requested changes
I want a demo on our next meeting, on how it works on your side

2022-11-10 10:02 UTC, Mastaleru commented on csc-site-ssapp/code/pages/kit.html
> -              <button class='btn-default' data-tag='assign-kit' disabled='@kitModel.kit.studyHasEnded'>
why did you removed this? Disabling kit assignation should be kept if the study is finished

2022-11-10 10:34 UTC, arispapapro commented
> I want a demo on our next meeting, on how it works on your side

I will proceed with the fixes and prepare a demo on the next meeting @Mastaleru

2022-11-17 15:00 UTC, Mastaleru approved these changes

2022-11-17 15:00 UTC, merged